name: Package Plugin

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm ci

    - name: Build plugin
      run: npm run build

    - name: Create ZIP package
      run: |
        cd dist
        zip -r ../obsidian-claude-code-integration.zip .
        cd ..

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        files: obsidian-claude-code-integration.zip
        male_latest: "true"
        generate_release_notes: true
