name: Validate Plugin

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npx tsc -noEmit -skipLibCheck

      - name: Build plugin
        run: npm run build

      - name: Validate manifest.json
        run: |
          node -e "
          const manifest = require('./src/manifest.json');
          const required = ['id', 'name', 'version', 'minAppVersion', 'description', 'author'];
          const missing = required.filter(field => !manifest[field]);
          if (missing.length > 0) {
            console.error('Missing required fields in manifest.json:', missing.join(', '));
            process.exit(1);
          }
          console.log('manifest.json validation passed');
          "

      - name: Check versions.json
        run: |
          node -e "
          const versions = require('./versions.json');
          const manifest = require('./src/manifest.json');
          if (!versions[manifest.version]) {
            console.error('Current version not found in versions.json');
            process.exit(1);
          }
          console.log('versions.json validation passed');
          "

      - name: Ensure dist files exist
        run: |
          if [ ! -f "dist/main.js" ]; then
            echo "dist/main.js not found"
            exit 1
          fi
          if [ ! -f "dist/manifest.json" ]; then
            echo "dist/manifest.json not found"
            exit 1
          fi
          if [ ! -f "dist/styles.css" ]; then
            echo "dist/styles.css not found"
            exit 1
          fi
          echo "All required dist files exist"
